os:
    - linux

sudo: required
dist: trusty

language: c

services:
    - docker

install:
    - docker-compose build --build-arg CHECK_CODE=${CHECK_CODE} --build-arg PG_VERSION=${PG_VERSION} tests

script:
    - docker-compose run tests

env:
    - PG_VERSION=10  CHECK_CODE=clang
    - PG_VERSION=10  CHECK_CODE=false
    - PG_VERSION=11  CHECK_CODE=clang
    - PG_VERSION=11  CHECK_CODE=false
    - PG_VERSION=12  CHECK_CODE=clang
    - PG_VERSION=12  CHECK_CODE=false
